# This is a workflow template to copy the securitycodescan workflow to user's repository

name: setup_securitycodescan

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      _entity_repository_metadata_Name:
        description: Select a repository
        required: true
        type: string

env:
  # this will be used as the description for the template entity in the dev platform
  description: This template setup security code scan workflow in user's repository

  TARGET_REPOSITORY: ${{ github.repository_owner }}/${{ inputs._entity_repository_metadata_Name }}
  TARGET_REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository_owner }}/${{ inputs._entity_repository_metadata_Name }}

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Generate branch name with datetime
        run: echo "BRANCH_NAME=securitycodescan-$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          path: main

      - uses: actions/checkout@v4
        with:
          path: securitycodescan
          repository: ${{ env.TARGET_REPOSITORY }}
          token: ${{ secrets.ORG_GITHUB_TOKEN }}

      - name: create copy_securitycodescan branch
        working-directory: securitycodescan
        run: |
          git branch $BRANCH_NAME
          git checkout $BRANCH_NAME

      - name: Copy Sample Workflow
        run: |
          mkdir -p securitycodescan/.github/workflows
          cp main/workflows/securitycodescan.yml securitycodescan/.github/workflows/securitycodescan.yml

      - name: Commit and Push
        working-directory: securitycodescan
        run: |
          git add .github/*
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -m "Add securitycodescan workflow"
          git push --set-upstream origin $BRANCH_NAME

      - name: Create pull request
        working-directory: securitycodescan
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
        run: |
          gh pr create --title "Add securitycodescan workflow" --body "Add securitycodescan workflow"
      
      - name: Done
        run: |
          echo done.
